### NumPy Introduction

1) NumPy: Numerical Python<br>2) A linear algebra library for Python. Utilized by a large number of other libraries in the Python ecosystem. Also very fast.<br>3) NumPy arrays come in two flavors: Vectors, and matrices<br>--Vectors are strictly 1-d arrays<br>--Matrices are 2-d ( you can still have a matrix with only one row or column)<br>

### NumPy Arrays

Can create a list and then cast it as a NumPy array

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

1-d array

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

To get a 2-d array, can pass a list of lists...2-d array can be identified by the number of outside brackets

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Creating NumPy arrays without Python lists

In [12]:
np.arange(0,10,2) #Starts at 0, up to but not including 10, with a step of 2

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3) #One dimensional vector of zeros

array([0., 0., 0.])

In [14]:
np.zeros((5,5)) #Tuple to pass in more than one dimension

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10) #Returns a range of numbers from the start to the stop, specified with your number of evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
# Single digit argument. Identity matrix useful for linear algebra problems. Number of rows is same as columns.
# Returns a diagonal of ones, everything else 0. Identity matrix must be square, which is the reason for one argument
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### Creating arrays of random numbers

In [27]:
# Creates an array of a given shape, and populate with random samples from a UNIFORM distribution. Ranging from 0 to 1
np.random.rand(5)

array([0.34083722, 0.98317075, 0.01198076, 0.94760358, 0.42235599])

In [28]:
np.random.rand(5,5)

array([[0.77934847, 0.25264436, 0.88201766, 0.12377619, 0.10120525],
       [0.51889027, 0.30052895, 0.69385115, 0.9659485 , 0.37910407],
       [0.51353453, 0.4369369 , 0.81979756, 0.87617658, 0.80968568],
       [0.89066692, 0.80832308, 0.44455481, 0.50284123, 0.07897868],
       [0.92301974, 0.53115179, 0.26879543, 0.57391301, 0.52556032]])

In [29]:
# Creating an array of random numbers from a NORMAL distribution
np.random.randn(2)

array([0.74269995, 0.63362701])

In [30]:
np.random.randn(2,5)

array([[ 0.30135888,  1.29716457,  0.63137752, -1.02255963, -0.49300398],
       [-0.67689523,  0.66802386,  0.60260483, -1.06386064, -0.31835348]])

In [32]:
#Generating random integer, (start, stop, number of integers you want returned)
np.random.randint(1,100, 15)

array([27, 58, 47, 32, 59,  1, 72, 53, 72,  7, 83, 84, 57, 71, 50])

##### Useful attributes or methods of an array

In [36]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,50,10)
ranarr

array([48, 42, 21, 40, 46,  7, 11, 14,  7, 36])

In [54]:
#Creating a new shape for our array, values remain same
#MUST have same number of values to fill array. Original is 25, and so is the reshaped version
#MUST re-assign the reshape to a variable to fully reshape it

arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
#MAX value within an array
ranarr.max()

48

In [44]:
#MIN value within an array
ranarr.min()

7

In [48]:
#Returns the index location of our MAX value
ranarr.argmax()

0

In [50]:
#Returns the index location of our MIN value
ranarr.argmin()

5

In [53]:
#Figuring out the shape of the array
arr.shape

(25,)

In [55]:
#Returning the data type of the array
arr.dtype

dtype('int32')