### NumPy Introduction

1) NumPy: Numerical Python<br>2) A linear algebra library for Python. Utilized by a large number of other libraries in the Python ecosystem. Also very fast.<br>3) NumPy arrays come in two flavors: Vectors, and matrices<br>--Vectors are strictly 1-d arrays<br>--Matrices are 2-d ( you can still have a matrix with only one row or column)<br>

[SciPy Documentation](https://docs.scipy.org/doc/)

### NumPy Arrays

Can create a list and then cast it as a NumPy array

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

1-d array

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

To get a 2-d array, can pass a list of lists...2-d array can be identified by the number of outside brackets

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Creating NumPy arrays without Python lists

In [7]:
np.arange(0,10,2) #Starts at 0, up to but not including 10, with a step of 2

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3) #One dimensional vector of zeros

array([0., 0., 0.])

In [9]:
np.zeros((5,5)) #Tuple to pass in more than one dimension

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10) #Returns a range of numbers from the start to the stop, specified with your number of evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
# Single digit argument. Identity matrix useful for linear algebra problems. Number of rows is same as columns.
# Returns a diagonal of ones, everything else 0. Identity matrix must be square, which is the reason for one argument
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### Creating arrays of random numbers

In [14]:
# Creates an array of a given shape, and populate with random samples from a UNIFORM distribution. Ranging from 0 to 1
np.random.rand(5)

array([0.59555133, 0.50556799, 0.73868277, 0.20491425, 0.81233445])

In [15]:
np.random.rand(5,5)

array([[0.4247226 , 0.15999609, 0.71734513, 0.64447135, 0.26972812],
       [0.86734743, 0.60623314, 0.12680285, 0.46360827, 0.78153726],
       [0.07830823, 0.64419004, 0.12567649, 0.06548447, 0.14166721],
       [0.45670218, 0.35590169, 0.81835885, 0.86780454, 0.49984485],
       [0.91349176, 0.1892698 , 0.19760629, 0.26745502, 0.98286932]])

In [16]:
# Creating an array of random numbers from a NORMAL distribution
np.random.randn(2)

array([-0.64244277,  0.9355789 ])

In [17]:
np.random.randn(2,5)

array([[-0.87032876,  0.41604373,  1.18165136,  0.02383819,  1.77171082],
       [-2.26358192,  0.51011281,  0.6019201 , -0.61654398, -2.4271175 ]])

In [18]:
#Generating random integer, (start, stop, number of integers you want returned)
np.random.randint(1,100, 15)

array([12, 70, 38, 43, 14, 83, 10, 75, 35, 92, 80, 97, 22,  2, 20])

##### Useful attributes or methods of an array

In [19]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)
ranarr

array([31,  3, 31,  6,  4,  7, 27, 25,  0,  9])

In [21]:
#Creating a new shape for our array, values remain same
#MUST have same number of values to fill array. Original is 25, and so is the reshaped version
#MUST re-assign the reshape to a variable to fully reshape it

arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
#MAX value within an array
ranarr.max()

31

In [23]:
#MIN value within an array
ranarr.min()

0

In [24]:
#Returns the index location of our MAX value
ranarr.argmax()

0

In [25]:
#Returns the index location of our MIN value
ranarr.argmin()

8

In [26]:
#Figuring out the shape of the array
arr.shape

(25,)

In [27]:
#Returning the data type of the array
arr.dtype

dtype('int32')

### NumPy Indexing & Selection

In [28]:
arr2 = np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr2[5] #Selecting a SINGLE element

5

In [30]:
arr2[1:5] #Selecting SEVERAL elements

array([1, 2, 3, 4])

In [31]:
arr2[:3] #Grabbing everything up to the specified index

array([0, 1, 2])

In [32]:
arr2[3:] #Grabbing everything beyond the specified index

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr2[0:3] = 100 #This is known as "Broadcasting", setting the first three elements = 100
arr2

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [34]:
slice_of_arr2 = arr2[0:6] #Assigning a slice of the array to a variable

In [35]:
slice_of_arr2[:] #Grabbing everything in that slice

array([100, 100, 100,   3,   4,   5])

In [36]:
slice_of_arr2[:] = 99 #Assigning 99 as the new values within slice
slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [37]:
arr2 #Showcasing the NumPy does NOT copy your array, overwrites it. 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
arr2_copy = arr2.copy() #Use .copy() to actually create a copy

##### Creating 2-d arrays (Matrix)

In [39]:
arr2_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
#Indexing begins at 0, and is inclusive for both indexes
arr2_2d[0,0] #Double-bracket format to grab values from 2-d array. FORMAT: [ROWS, COLUMNS]

5

In [59]:
#Explanation: With the indexing below, we use 0:2 to grab rows starting at index 0, and up to but not 
#including row 3 (which is index 2), and then we use 1 in the column portion to grab values at column index 1 
#(which is visually, column 2)

arr2_2d[0:2,1] #[ROWS, COLUMNS]

array([10, 25])

### Numpy Operations

In [80]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Simple math operations on an array, on an element by element basis

In [42]:
arr3 + arr3 #Addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
arr3 - arr3 #Subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
arr3 * arr3 #Multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

##### Broadcasts to each element in the array, doing on operation to each element

In [45]:
arr3 + 100 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [46]:
arr3 - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [47]:
arr3 * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [48]:
arr3 / arr3 #Showcasing div/0 warning, not an error like it would be in Python

C:\Users\troyf\AppData\Local\Temp/ipykernel_25220/3756652605.py:1: RuntimeWarning: invalid value encountered in divide
  arr3 / arr3 #Showcasing div/0 warning, not an error like it would be in Python


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
1 / arr3 #Shows that 1 / 0 results in the inf value

C:\Users\troyf\AppData\Local\Temp/ipykernel_25220/33658666.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr3 #Shows that 1 / 0 results in the inf value


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [50]:
arr3 ** 2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
np.sqrt(arr3) #Taking square root of every element in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [52]:
np.exp(arr3) #Exponentional, Eulers Number: 2.71828183e+00, taking exponential of each number in array and multiplying by Euler's

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [53]:
arr3.max() #Maximum value

10

In [54]:
np.max(arr3) #Maximum value

10

In [55]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [56]:
np.log(arr3)

C:\Users\troyf\AppData\Local\Temp/ipykernel_25220/2430430252.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [81]:
arr4 = arr3.copy()

In [84]:
arr4 = arr4.reshape(3,3)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr4.sum(axis=0) #Summing values by columns

array([12, 15, 18])